import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://demowebshop.tricentis.com/');
    await page.getByRole('link', { name: 'Books' }).nth(1).click();
    await page.getByRole('button', { name: 'Add to cart' }).first().click();
    await page.getByRole('link', { name: 'Shopping cart (1)' }).click();
    await page.getByLabel('Country:').selectOption('2');
    await page.getByLabel('State / province:').selectOption('65');
    await page.locator('#termsofservice').check();
    await page.getByRole('button', { name: 'Checkout' }).click();
    await page.getByRole('textbox', { name: 'Email:' }).click();
    await page.getByRole('textbox', { name: 'Email:' }).fill('barkavirag@gmail.com');
    await page.getByRole('textbox', { name: 'Email:' }).press('Tab');
    await page.getByRole('textbox', { name: 'Password:' }).fill('barkavirag');
    await page.getByRole('button', { name: 'Log in' }).click();
    await page.getByLabel('Country:').selectOption('2');
    await page.getByLabel('State / province:').selectOption('65');
    await page.locator('#termsofservice').check();
    await page.getByRole('button', { name: 'Checkout' }).click();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('paragraph').filter({ hasText: 'In-Store Pickup' }).click();
    await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('heading', { name: 'Billing address' }).click();
    await page.getByLabel('Select a billing address from').selectOption('');
    await page.getByRole('textbox', { name: 'Company:' }).click();
    await page.getByRole('textbox', { name: 'Company:' }).fill('valami kft');
    await page.getByRole('textbox', { name: 'City:' }).click();
    await page.getByRole('textbox', { name: 'City:' }).fill('Kalocsa');
    await page.getByRole('textbox', { name: 'Address 1:' }).click();
    await page.getByRole('textbox', { name: 'Address 1:' }).fill('Valami');
    await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
    await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('6300');
    await page.getByRole('textbox', { name: 'Phone number:' }).click();
    await page.getByRole('textbox', { name: 'Phone number:' }).fill('+3634234324');
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.locator('#BillingNewAddress_CountryId').selectOption('2');
    await page.locator('#BillingNewAddress_StateProvinceId').selectOption('65');
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('radio', { name: 'Check / Money Order (5.00)' }).check();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByText('10.00').nth(2).click();
    await page.getByText('Sub-Total:', { exact: true }).click();
    await page.getByText('10.00').nth(4).click();
    await page.getByText('Payment method additional fee:').click();
    await page.getByText('5.00', { exact: true }).click();
    await page.getByRole('cell', { name: 'Total:', exact: true }).locator('span').click();
    await page.getByText('15.00').click();
    await page.getByRole('button', { name: 'Confirm' }).click();
    await page.getByText('Your order has been').click();
    await page.getByText('Order number:').click();
    await page.getByRole('link', { name: 'Click here for order details.' }).click();
});